version: '1.0'
enabled: true
requirements:
  commit_plan:
    enabled: true
    type: blocking
    scope: session
    description: "Ensures an atomic commit strategy exists before implementation."
    trigger_tools:
    - Edit
    - Write
    - MultiEdit
    auto_resolve_skill: "requirements-framework:arch-review"
    message: |
      ## Blocked: commit_plan

      **Execute**: `/{auto_resolve_skill}`

      Team-based architecture review with commit planning and cross-validation.
    checklist:
    - Identified the changes needed
    - Determined atomic commit boundaries
    - Planned commit sequence
  adr_reviewed:
    enabled: true
    type: blocking
    scope: session
    description: "Ensures changes align with Architecture Decision Records."
    trigger_tools:
    - Edit
    - Write
    - MultiEdit
    auto_resolve_skill: "requirements-framework:arch-review"
    message: |
      ## Blocked: adr_reviewed

      **Execute**: `/{auto_resolve_skill}`

      Team-based ADR review with cross-validation against breaking changes and testability.
    checklist:
    - Searched for ADRs related to this change
    - Confirmed approach aligns with existing ADRs
  tdd_planned:
    enabled: true
    type: blocking
    scope: session
    description: "Ensures the plan includes TDD strategy and test cases per feature."
    trigger_tools:
    - Edit
    - Write
    - MultiEdit
    auto_resolve_skill: "requirements-framework:arch-review"
    message: |
      ## Blocked: tdd_planned

      **Execute**: `/{auto_resolve_skill}`

      Team-based TDD validation with cross-reference against breaking changes.
    checklist:
    - Plan has a testing strategy section
    - Each feature identifies tests to write first
    - TDD sequence is documented
  solid_reviewed:
    enabled: true
    type: blocking
    scope: session
    description: "Ensures the plan follows SOLID principles with Python-specific patterns."
    trigger_tools:
    - Edit
    - Write
    - MultiEdit
    auto_resolve_skill: "requirements-framework:arch-review"
    message: |
      ## Blocked: solid_reviewed

      **Execute**: `/{auto_resolve_skill}`

      Team-based SOLID review with cross-validation against testability and ADRs.
    checklist:
    - "Plan reviewed for Single Responsibility (no mixed concerns)"
    - "Extension points identified where applicable (Open/Closed)"
    - "Dependencies use abstractions not concretions (Dependency Inversion)"
  protected_branch:
    enabled: true
    type: guard
    guard_type: protected_branch
    description: "Prevents direct edits on main/master branches."
    protected_branches:
    - master
    - main
    trigger_tools:
    - Edit
    - Write
    - MultiEdit
    message: |
      ## Blocked: protected_branch

      Cannot edit files on protected branch `{branch}`.

      **Actions**:
      1. Create feature branch: `git checkout -b feature/your-feature-name`
      2. Emergency override: `req approve protected_branch`
    checklist:
    - Confirmed not on protected branch (master/main)
    - Feature branch created for changes
  branch_size_limit:
    enabled: true
    type: dynamic
    calculator: branch_size_calculator
    description: "Automatically calculates branch size and enforces PR size limits."
    scope: session
    trigger_tools:
    - Edit
    - Write
    - MultiEdit
    cache_ttl: 60
    approval_ttl: 3600
    thresholds:
      warn: 250
      block: 400
    blocking_message: |
      ## Blocked: branch_size_limit

      Branch has **{total}** line changes (limit: {block_threshold}).

      {summary}

      **Recommendation**: Split into smaller, focused PRs after this session.

      ---
      Override: `req approve branch_size_limit`
  single_session_per_project:
    enabled: true
    type: guard
    guard_type: single_session
    description: "Prevents multiple sessions from editing the same project simultaneously."
    scope: session
    trigger_tools:
      - Edit
      - Write
      - MultiEdit
    message: |
      ## Blocked: single_session_per_project

      Another Claude Code session is active on this project.

      **Actions**:
      1. Close the other session
      2. Wait for completion
      3. Override: `req approve single_session_per_project`
    checklist:
      - "Confirmed no other active sessions on this project"
  pre_commit_review:
    enabled: true
    type: blocking
    scope: single_use
    description: "Code review before each commit - resets after commit completes."
    trigger_tools:
    - tool: Bash
      command_pattern: git\s+(commit|cherry-pick|revert|merge)
    auto_resolve_skill: "requirements-framework:pre-commit"
    satisfied_by_skill: "requirements-framework:pre-commit"
    message: |
      ## Blocked: pre_commit_review

      **Execute**: `/{auto_resolve_skill}`

      Runs code-reviewer, silent-failure-hunter, and tool-validator agents.
    checklist:
    - Code follows project conventions
    - Error handling is adequate
    - No obvious bugs or issues
  pre_pr_review:
    enabled: true
    type: blocking
    scope: single_use
    description: "Comprehensive quality review with all review agents before PR creation."
    trigger_tools:
    - tool: Bash
      command_pattern: gh\s+pr\s+create
    auto_resolve_skill: "requirements-framework:deep-review"
    satisfied_by_skill: "requirements-framework:deep-review"
    message: |
      ## Blocked: pre_pr_review

      **Execute**: `/{auto_resolve_skill}`

      Cross-validated team-based review with agent debate.
    checklist:
    - Code has been reviewed for bugs
    - Error handling is complete
    - Tests are adequate (if applicable)
  codex_reviewer:
    enabled: true
    type: blocking
    scope: single_use
    description: "AI-powered code review via OpenAI Codex CLI before PR creation."
    trigger_tools:
    - tool: Bash
      command_pattern: gh\s+pr\s+create
    auto_resolve_skill: "requirements-framework:codex-review"
    satisfied_by_skill: "requirements-framework:codex-review"
    message: |
      ## Blocked: codex_reviewer

      **Execute**: `/{auto_resolve_skill}`

      AI-powered code review via OpenAI Codex CLI.
    checklist:
    - Codex CLI installed (npm install -g @openai/codex)
    - AI review completed

hooks:
  session_start:
    inject_context: true
    injection_mode: auto
  session_learning:
    enabled: true
    prompt_on_stop: true
    min_tool_uses: 5
  stop:
    verify_requirements: true
inherit: true
